import { Department, TeacherDesignation } from "../generated/prisma/enums";

export const teachers = [
  {
    email: "jamalpstu07@gmail.com",
    name: "Mohammad Jamal Hossain",
    password: "SecurePassword123",
    phoneNumber: "01760337440",
    address: "Dumki, Patuakhali, Bangladesh",
    faculty: "Faculty of Computer Science and Engineering",
    department: Department.Computer_Science_And_Information_Technology,
    joinedAt: new Date("2023-01-15T00:00:00Z"),
    designation: TeacherDesignation.PROFESSOR,
    isChairman: false,
    photoUrl: "https://pstu.ac.bd/images/default.jpg"
  },
  {
    email: "masud@pstu.ac.bd",
    name: "Dr. Md Abdul Masud",
    password: "SecurePassword123",
    phoneNumber: "+8801887-826804",
    address: "Dumki, Patuakhali, Bangladesh",
    faculty: "Faculty of Computer Science and Engineering",
    department: Department.Computer_Science_And_Information_Technology,
    joinedAt: new Date("2007-01-01T00:00:00Z"),
    designation: TeacherDesignation.PROFESSOR,
    isChairman: false,
    photoUrl: "https://pstu.ac.bd/images/default.jpg"
  },
  {
    email: "chinmay.cse@pstu.ac.bd",
    name: "Professor Chinmay Bepery",
    password: "SecurePassword123",
    phoneNumber: "+8801922361666",
    address: "Dumki, Patuakhali, Bangladesh",
    faculty: "Faculty of Computer Science and Engineering",
    department: Department.Computer_Science_And_Information_Technology,
    joinedAt: new Date("2010-09-01T00:00:00Z"),
    designation: TeacherDesignation.PROFESSOR,
    isChairman: false,
    photoUrl: "https://pstu.ac.bd/images/default.jpg"
  },
  {
    email: "atik.csit@pstu.ac.bd",
    name: "Md Atikqur Rahaman",
    password: "SecurePassword123",
    phoneNumber: "01915114929",
    address: "Dumki, Patuakhali, Bangladesh",
    faculty: "Faculty of Computer Science and Engineering",
    department: Department.Computer_Science_And_Information_Technology,
    joinedAt: new Date("2011-01-01T00:00:00Z"),
    designation: TeacherDesignation.PROFESSOR,
    isChairman: false,
    photoUrl: "https://pstu.ac.bd/images/default.jpg"
  },
  {
    email: "mahbub.cse@pstu.ac.bd",
    name: "Md Mahbubur Rahman",
    password: "SecurePassword123",
    phoneNumber: "+8801556449873",
    address: "Dumki, Patuakhali, Bangladesh",
    faculty: "Faculty of Computer Science and Engineering",
    department: Department.Computer_Science_And_Information_Technology,
    joinedAt: new Date("2018-01-01T00:00:00Z"),
    designation: TeacherDesignation.ASSOCIATE_PROFESSOR,
    isChairman: false,
    photoUrl: "https://pstu.ac.bd/images/default.jpg"
  },
  {
    email: "teacher6@example.com",
    name: "Moinul Islam Sayed",
    password: "SecurePassword123",
    phoneNumber: "01700000000",
    address: "Dumki, Patuakhali, Bangladesh",
    faculty: "Faculty of Computer Science and Engineering",
    department: Department.Computer_Science_And_Information_Technology,
    joinedAt: new Date("2023-01-15T00:00:00Z"),
    designation: TeacherDesignation.ASSISTANT_PROFESSOR,
    isChairman: false,
    photoUrl: "https://pstu.ac.bd/images/default.jpg"
  },
  {
    email: "mim@pstu.ac.bd",
    name: "Dr. Farjana Sultana Mim",
    password: "SecurePassword123",
    phoneNumber: "+8801306797914",
    address: "Dumki, Patuakhali, Bangladesh",
    faculty: "Faculty of Computer Science and Engineering",
    department: Department.Computer_Science_And_Information_Technology,
    joinedAt: new Date("2023-01-15T00:00:00Z"),
    designation: TeacherDesignation.LECTURER,
    isChairman: false,
    photoUrl: "https://pstu.ac.bd/images/default.jpg"
  },
  {
    email: "muhtasim.cse@pstu.ac.bd",
    name: "Muhtasim",
    password: "SecurePassword123",
    phoneNumber: "+8801521303222",
    address: "Dumki, Patuakhali, Bangladesh",
    faculty: "Faculty of Computer Science and Engineering",
    department: Department.Computer_Science_And_Information_Technology,
    joinedAt: new Date("2025-06-01T00:00:00Z"),
    designation: TeacherDesignation.LECTURER,
    isChairman: false,
    photoUrl: "https://pstu.ac.bd/images/default.jpg"
  },
  {
    email: "murad@pstu.ac.bd",
    name: "Golam Md. Muradul Bashir",
    password: "SecurePassword123",
    phoneNumber: "01718323601",
    address: "Dumki, Patuakhali, Bangladesh",
    faculty: "Faculty of Computer Science and Engineering",
    department: Department.Computer_science_And_Communication_Engineering,
    joinedAt: new Date("2006-01-01T00:00:00Z"),
    designation: TeacherDesignation.PROFESSOR,
    isChairman: true,
    photoUrl: "https://pstu.ac.bd/images/default.jpg"
  },
  {
    email: "sobuz@pstu.ac.bd",
    name: "Dr.Md.Samsuzzaman",
    password: "SecurePassword123",
    phoneNumber: "+8801712653210",
    address: "Dumki, Patuakhali, Bangladesh",
    faculty: "Faculty of Computer Science and Engineering",
    department: Department.Computer_science_And_Communication_Engineering,
    joinedAt: new Date("2008-01-01T00:00:00Z"),
    designation: TeacherDesignation.PROFESSOR,
    isChairman: false,
    photoUrl: "https://pstu.ac.bd/images/default.jpg"
  },
  {
    email: "saran.majumder90@gmail.com",
    name: "Sarna Majumder",
    password: "SecurePassword123",
    phoneNumber: "01767265119",
    address: "Dumki, Patuakhali, Bangladesh",
    faculty: "Faculty of Computer Science and Engineering",
    department: Department.Computer_science_And_Communication_Engineering,
    joinedAt: new Date("2015-01-01T00:00:00Z"),
    designation: TeacherDesignation.ASSOCIATE_PROFESSOR,
    isChairman: false,
    photoUrl: "https://pstu.ac.bd/images/default.jpg"
  }
];
